name: Check PHP Coding Standards

on:
  workflow_call:
    secrets:
      GITHUB_PAT:
        required: true
        description: GitHub Personal Access Token.

defaults:
  run:
    shell: bash

jobs:
  phpcs:
    name: Checking standards
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: 7.4
          tools: composer

      - name: Tool versions
        run: |
          php --version
          composer --version

      - uses: koilabcode/wc-extension-workflows/.github/actions/install-composer-deps@main
        with:
          workflow_name: check-phpcs
          github_pat: ${{ secrets.GITHUB_PAT }}

      - name: Run PHP_CodeSniffer
        uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: vendor/bin/phpcs
          standard: phpcs.xml
